export const CREATE_DT_REQUEST = 'CREATE_DT_REQUEST';
export const CREATE_DT_SUCCESS = 'CREATE_DT_SUCCESS';
export const CREATE_DT_FAILURE = 'CREATE_DT_FAILURE';
export const CREATE_DT_RESET = 'CREATE_DT_RESET';