export const STUDENT_REGISTER_ACTIVE_REQUEST =  'STUDENT_REGISTER_ACTIVE_REQUEST';
export const STUDENT_REGISTER_ACTIVE_SUCCESS =  'STUDENT_REGISTER_ACTIVE_SUCCESS';
export const STUDENT_REGISTER_ACTIVE_FAILURE =  'STUDENT_REGISTER_ACTIVE_FAILURE';