export const ACCEPT_ACTIVITY_BY_STUDENT_REQUEST = 'ACCEPT_ACTIVITY_BY_STUDENT_REQUEST';
export const ACCEPT_ACTIVITY_BY_STUDENT_SUCCESS = 'ACCEPT_ACTIVITY_BY_STUDENT_SUCCESS';
export const ACCEPT_ACTIVITY_BY_STUDENT_FAILURE = 'ACCEPT_ACTIVITY_BY_STUDENT_FAILURE';
export const ACCEPT_ACTIVITY_BY_STUDENT_RESET = 'ACCEPT_ACTIVITY_BY_STUDENT_RESET';

