export const ACCEPT_ACTIVITY_BY_DT_REQUEST = 'ACCEPT_ACTIVITY_BY_DT_REQUEST';
export const ACCEPT_ACTIVITY_BY_DT_SUCCESS = 'ACCEPT_ACTIVITY_BY_DT_SUCCESS';
export const ACCEPT_ACTIVITY_BY_DT_FAILURE = 'ACCEPT_ACTIVITY_BY_DT_FAILURE';
export const ACCEPT_ACTIVITY_BY_DT_RESET = 'ACCEPT_ACTIVITY_BY_DT_RESET';

