export const REGISTER_ACTIVE_REQUEST = 'REGISTER_ACTIVE_REQUEST';
export const REGISTER_ACTIVE_SUCCESS = 'REGISTER_ACTIVE_SUCCESS';
export const REGISTER_ACTIVE_FAILURE = 'REGISTER_ACTIVE_FAILURE';
export const REGISTER_ACTIVE_RESET = 'REGISTER_ACTIVE_RESET';