export const CANCEL_ACTIVE_REQUEST = 'CANCEL_ACTIVE_REQUEST';
export const CANCEL_ACTIVE_SUCCESS = 'CANCEL_ACTIVE_SUCCESS';
export const CANCEL_ACTIVE_FAILURE = 'CANCEL_ACTIVE_FAILURE';
export const CANCEL_ACTIVE_RESET = 'CANCEL_ACTIVE_RESET';