export const LIST_ACTIVE_THONGKE_REQUEST = 'LIST_ACTIVE_THONGKE_REQUEST';
export const LIST_ACTIVE_THONGKE_SUCCESS = 'LIST_ACTIVE_THONGKE_SUCCESS';
export const LIST_ACTIVE_THONGKE_FAILURE = 'LIST_ACTIVE_THONGKE_FAILURE';