export const GET_USER_STUDENT_REQUEST = 'GET_USER_STUDENT_REQUEST';
export const GET_USER_STUDENT_SUCCESS = 'GET_USER_STUDENT_SUCCESS';
export const GET_USER_STUDENT_FAILURE = 'GET_USER_STUDENT_FAILURE';