export const CREATE_ACTIVE_REQUEST = 'CREATE_ACTIVE_REQUEST';
export const CREATE_ACTIVE_SUCCESS = 'CREATE_ACTIVE_SUCCESS';
export const CREATE_ACTIVE_FAILURE = 'CREATE_ACTIVE_FAILURE';
export const CREATE_ACTIVE_RESET = 'CREATE_ACTIVE_RESET';