export const GET_USER_STUDENT_DT_REQUEST = 'GET_USER_STUDENT_DT_REQUEST';
export const GET_USER_STUDENT_DT_SUCCESS = 'GET_USER_STUDENT_DT_SUCCESS';
export const GET_USER_STUDENT_DT_FAILURE = 'GET_USER_STUDENT_DT_FAILURE';