export const LIST_ACTIVE_CREATED_REQUEST = 'LIST_ACTIVE_CREATED_REQUEST';
export const LIST_ACTIVE_CREATED_SUCCESS = 'LIST_ACTIVE_CREATED_SUCCESS';
export const LIST_ACTIVE_CREATED_FAILURE = 'LIST_ACTIVE_CREATED_FAILURE';