export const APPROVE_STUDENT_REGISTER_REQUEST = 'APPROVE_STUDENT_REGISTER_REQUEST';
export const APPROVE_STUDENT_REGISTER_SUCCESS = 'APPROVE_STUDENT_REGISTER_SUCCESS';
export const APPROVE_STUDENT_REGISTER_FAILURE = 'APPROVE_STUDENT_REGISTER_FAILURE';
export const APPROVE_STUDENT_REGISTER_RESET = 'APPROVE_STUDENT_REGISTER_RESET';

