export const ACTIVE_PARTICIPATED_REQUEST = 'ACTIVE_PARTICIPATED_REQUEST';
export const ACTIVE_PARTICIPATED_SUCCESS = 'ACTIVE_PARTICIPATED_SUCCESS';
export const ACTIVE_PARTICIPATED_FAILURE = 'ACTIVE_PARTICIPATED_FAILURE';