export const NOTIFICATION_STUDENT_DT_REQUEST = ' NOTIFICATION_STUDENT_DT_REQUEST';
export const NOTIFICATION_STUDENT_DT_SUCCESS = ' NOTIFICATION_STUDENT_DT_SUCCESS';
export const NOTIFICATION_STUDENT_DT_FAILURE = ' NOTIFICATION_STUDENT_DT_FAILURE';