export const LOCK_ACCOUNT_REQUEST = 'LOCK_ACCOUNT_REQUEST';
export const LOCK_ACCOUNT_SUCCESS = 'LOCK_ACCOUNT_SUCCESS';
export const LOCK_ACCOUNT_FAILURE = 'LOCK_ACCOUNT_FAILURE';
export const LOCK_ACCOUNT_RESET = 'LOCK_ACCOUNT_RESET';