export const EDIT_ACTIVE_REQUEST = 'EDIT_ACTIVE_REQUEST';
export const EDIT_ACTIVE_SUCCESS = 'EDIT_ACTIVE_SUCCESS';
export const EDIT_ACTIVE_FAILURE = 'EDIT_ACTIVE_FAILURE';
export const EDIT_ACTIVE_RESET = 'EDIT_ACTIVE_RESET';