export const REMOVE_ACTIVE_REQUEST = 'REMOVE_ACTIVE_REQUEST';
export const REMOVE_ACTIVE_SUCCESS = 'REMOVE_ACTIVE_SUCCESS';
export const REMOVE_ACTIVE_FAILURE = 'REMOVE_ACTIVE_FAILURE';
export const REMOVE_ACTIVE_RESET = 'REMOVE_ACTIVE_RESET';