export const EDIT_STUDENT_REQUEST = 'EDIT_STUDENT_REQUEST';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';
export const EDIT_STUDENT_FAILURE = 'EDIT_STUDENT_FAILURE';
export const EDIT_STUDENT_RESET = 'EDIT_STUDENT_RESET';

