export const THONG_KE_ACTIVE_REQUEST = 'THONG_KE_ACTIVE_REQUEST';
export const THONG_KE_ACTIVE_SUCCESS = 'THONG_KE_ACTIVE_SUCCESS';
export const THONG_KE_ACTIVE_FAILURE = 'THONG_KE_ACTIVE_FAILURE';
export const THONG_KE_ACTIVE_RESET = 'THONG_KE_ACTIVE_RESET';