export const THONG_KE_ACTIVE_TRUONGCLB_REQUEST = 'THONG_KE_ACTIVE_TRUONGCLB_REQUEST';
export const THONG_KE_ACTIVE_TRUONGCLB_SUCCESS = 'THONG_KE_ACTIVE_TRUONGCLB_SUCCESS';
export const THONG_KE_ACTIVE_TRUONGCLB_FAILURE = 'THONG_KE_ACTIVE_TRUONGCLB_FAILURE';
export const THONG_KE_ACTIVE_TRUONGCLB_RESET = 'THONG_KE_ACTIVE_TRUONGCLB_RESET';