export default{
    colorTextMain: '#49688D',
    colorBorder: '#3669A4',
    colorBtn: 'white',
    colorLight: 'rgb(234,235,238)',
    colorBgUiTap: '#caf8fb',
    inactive: 'rgb(129,129,129)',
    colorRemove: '#ff7a7a',
    colorDecorateStep: '#55a6ff',
    colorBtnCreateActive: '#1fafb0',
    colorBgIconHome: '#eaeaea',
    colorApproveAll: '#41B06E',
    colorTextLock: '#FFA62F',
    colorTextUnLock: '#399590',
    colorBtnLock: '#fff5e7',
    colorBtnUnLock: '#d9fcfe',
    colorBtnRemove: '#ffecec',
    colorBtnEditAccount: '#e6fff0',
    colorBtnEditInfo: '#dbebff',
    
}